# Generated by Django 5.1.2 on 2024-12-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_attachment_tasklist_task_task_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creared_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='creared_on',
            new_name='created_on',
        ),
    ]
