# Generated by Django 5.1.2 on 2024-12-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='completed_task_count',
            new_name='completed_tasks_count',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='create_on',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='notcompleted_task_count',
            new_name='notcompleted_tasks_count',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='point',
            new_name='points',
        ),
    ]
